# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe302c34e40eeea71fcb82a1a918f9df54f2419cfcb6974d5fba6a4415e0089d7a2c410912fcf9358910038eb2a536ae295d6f937b6985ca73dea02852febd7a

test:
  secret_key_base: 99da3316f366e0d3f1f370019ff54c38d470f941dcac5489f4336559b502cbdb2b3de48eda83f7460726f146ae1002d55c63cdbf9c4e03232da545213c21c1ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
