# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d3346fe373094ad00522c254ad05b2a1324aca18a99ffd8015d5c0c39f79097dcbe210235bd355dda1f0fc6a1f31f6b93f8ee3038b31a74652a4b58a6d764b7

test:
  secret_key_base: bdc7b79a73cf7622eaf534184c9dcc01bb8e0ef6a321283f5c76c8944a2ca74e897619e4fca01e32b5e999fc21147ea9598b3c46bb7778b8453dec53fc0264de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
