# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3c7087feecffce774069b4fe3c7f82a21ebd2d94dbe79dc1164b15f938b213979b03f247cabb9c0c02777e11b2e351570852e5d82050fcfe37758006a5cd9eb

test:
  secret_key_base: 6c4968f37ac8471a20a97d3b56af43f4a6390f935318d4ee5cbed5d1acd9f9e52fa8218bfdf37484b32556d60ec22fd03f0461a8943c1e88b6f7a34ea2ac065a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
