# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 309730db8f5720bba22e4fe090020a88255728d048202e2e8957b7c88157296377439c73d073c0f158d66384cb38d26e0e7d81f6c3189e3ac001989255ea4494

test:
  secret_key_base: 5055fe587d284c4d793cf30c65eab6a3db15c69315bf7f41998e99a989c035d78dfc19f6990fee3ace8fd5999dd7f1368ed68de8f1cc758b939af889d1ad9ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
